### ISSUE TITLE
Willowbark spheres

### ISSUE THREAD

**Issue by dazdya** [nihlaeth/dnd#14]
Willowbark is unique among the prayers, in that it is in two spheres and has two circles. It is in all, at the 2nd circle, and in healing, at the 1st circle. How should I handle that?

**Comment by nihlaeth** [comment]
For now, just add it twice with a unique name (e.g. willowbark & willowbark-I).

It's not exactly an elegant solution, but I have yet to think of something that won't needlessly complicate the back-end code.
